bench-mz: CC=/home/noah/programs/opensource/gcc-dev/gcc-mz/bin/gcc
bench-mm: CC=/home/noah/programs/opensource/gcc-dev/gcc-mm/bin/gcc

bench-mz bench-mm bench:
	i=1 ; while [ $$i -le 100 ] ; do \
		$(CC) -O2 -c 0.c -o 0.o ; \
		i=$$((i + 1)) ; \
	done

build-mz: CC=/home/noah/programs/opensource/gcc-dev/gcc-mz/bin/gcc
build-mm: CC=/home/noah/programs/opensource/gcc-dev/gcc-mm/bin/gcc

build-mz build-mm build:
	$(CC) -O2 -c 0.c -o 0.o
	$(CC) -O2 -c 1.c -o 1.o
	$(CC) -O2 -c 2.c -o 2.o
	$(CC) -O2 -c 3.c -o 3.o
	$(CC) -O2 -c 4.c -o 4.o
	$(CC) -O2 -c 5.c -o 5.o
	$(CC) -O2 -c 6.c -o 6.o
	$(CC) -O2 -c 7.c -o 7.o
	$(CC) -O2 -c 8.c -o 8.o
	$(CC) -O2 -c 9.c -o 9.o
	$(CC) -O2 -c 10.c -o 10.o
	$(CC) -O2 -c 11.c -o 11.o
	$(CC) -O2 -c 12.c -o 12.o
	$(CC) -O2 -c 13.c -o 13.o
	$(CC) -O2 -c 14.c -o 14.o
	$(CC) -O2 -c 15.c -o 15.o
	$(CC) -O2 -c 16.c -o 16.o
	$(CC) -O2 -c 17.c -o 17.o
	$(CC) -O2 -c 18.c -o 18.o
	$(CC) -O2 -c 19.c -o 19.o
	$(CC) -O2 -c 20.c -o 20.o
	$(CC) -O2 -c 21.c -o 21.o
	$(CC) -O2 -c 22.c -o 22.o
	$(CC) -O2 -c 23.c -o 23.o
	$(CC) -O2 -c 24.c -o 24.o
	$(CC) -O2 -c 25.c -o 25.o
	$(CC) -O2 -c 26.c -o 26.o
	$(CC) -O2 -c 27.c -o 27.o
	$(CC) -O2 -c 28.c -o 28.o
	$(CC) -O2 -c 29.c -o 29.o
	$(CC) -O2 -c 30.c -o 30.o
	$(CC) -O2 -c 31.c -o 31.o
	$(CC) -O2 -c 32.c -o 32.o
	$(CC) -O2 -c 33.c -o 33.o
	$(CC) -O2 -c 34.c -o 34.o
	$(CC) -O2 -c 35.c -o 35.o
	$(CC) -O2 -c 36.c -o 36.o
	$(CC) -O2 -c 37.c -o 37.o
	$(CC) -O2 -c 38.c -o 38.o
	$(CC) -O2 -c 39.c -o 39.o
	$(CC) -O2 -c 40.c -o 40.o
	$(CC) -O2 -c 41.c -o 41.o
	$(CC) -O2 -c 42.c -o 42.o
	$(CC) -O2 -c 43.c -o 43.o
	$(CC) -O2 -c 44.c -o 44.o
	$(CC) -O2 -c 45.c -o 45.o
	$(CC) -O2 -c 46.c -o 46.o
	$(CC) -O2 -c 47.c -o 47.o
	$(CC) -O2 -c 48.c -o 48.o
	$(CC) -O2 -c 49.c -o 49.o
	$(CC) -O2 -c 50.c -o 50.o
	$(CC) -O2 -c 51.c -o 51.o
	$(CC) -O2 -c 52.c -o 52.o
	$(CC) -O2 -c 53.c -o 53.o
	$(CC) -O2 -c 54.c -o 54.o
	$(CC) -O2 -c 55.c -o 55.o
	$(CC) -O2 -c 56.c -o 56.o
	$(CC) -O2 -c 57.c -o 57.o
	$(CC) -O2 -c 58.c -o 58.o
	$(CC) -O2 -c 59.c -o 59.o
	$(CC) -O2 -c 60.c -o 60.o
	$(CC) -O2 -c 61.c -o 61.o
	$(CC) -O2 -c 62.c -o 62.o
	$(CC) -O2 -c 63.c -o 63.o
	$(CC) -O2 -c 64.c -o 64.o
	$(CC) -O2 -c 65.c -o 65.o
	$(CC) -O2 -c 66.c -o 66.o
	$(CC) -O2 -c 67.c -o 67.o
	$(CC) -O2 -c 68.c -o 68.o
	$(CC) -O2 -c 69.c -o 69.o
	$(CC) -O2 -c 70.c -o 70.o
	$(CC) -O2 -c 71.c -o 71.o
	$(CC) -O2 -c 72.c -o 72.o
	$(CC) -O2 -c 73.c -o 73.o
	$(CC) -O2 -c 74.c -o 74.o
	$(CC) -O2 -c 75.c -o 75.o
	$(CC) -O2 -c 76.c -o 76.o
	$(CC) -O2 -c 77.c -o 77.o
	$(CC) -O2 -c 78.c -o 78.o
	$(CC) -O2 -c 79.c -o 79.o
	$(CC) -O2 -c 80.c -o 80.o
	$(CC) -O2 -c 81.c -o 81.o
	$(CC) -O2 -c 82.c -o 82.o
	$(CC) -O2 -c 83.c -o 83.o
	$(CC) -O2 -c 84.c -o 84.o
	$(CC) -O2 -c 85.c -o 85.o
	$(CC) -O2 -c 86.c -o 86.o
	$(CC) -O2 -c 87.c -o 87.o
	$(CC) -O2 -c 88.c -o 88.o
	$(CC) -O2 -c 89.c -o 89.o
	$(CC) -O2 -c 90.c -o 90.o
	$(CC) -O2 -c 91.c -o 91.o
	$(CC) -O2 -c 92.c -o 92.o
	$(CC) -O2 -c 93.c -o 93.o
	$(CC) -O2 -c 94.c -o 94.o
	$(CC) -O2 -c 95.c -o 95.o
	$(CC) -O2 -c 96.c -o 96.o
	$(CC) -O2 -c 97.c -o 97.o
	$(CC) -O2 -c 98.c -o 98.o
	$(CC) -O2 -c 99.c -o 99.o

link-mz: CC=/home/noah/programs/opensource/gcc-dev/gcc-mz/bin/gcc
link-mm: CC=/home/noah/programs/opensource/gcc-dev/gcc-mm/bin/gcc

link-mz link-mm link: build
	$(CC) -O2 -c main.c -o main.o
	$(CC) main.o \
	0.o \
	1.o \
	2.o \
	3.o \
	4.o \
	5.o \
	6.o \
	7.o \
	8.o \
	9.o \
	10.o \
	11.o \
	12.o \
	13.o \
	14.o \
	15.o \
	16.o \
	17.o \
	18.o \
	19.o \
	20.o \
	21.o \
	22.o \
	23.o \
	24.o \
	25.o \
	26.o \
	27.o \
	28.o \
	29.o \
	30.o \
	31.o \
	32.o \
	33.o \
	34.o \
	35.o \
	36.o \
	37.o \
	38.o \
	39.o \
	40.o \
	41.o \
	42.o \
	43.o \
	44.o \
	45.o \
	46.o \
	47.o \
	48.o \
	49.o \
	50.o \
	51.o \
	52.o \
	53.o \
	54.o \
	55.o \
	56.o \
	57.o \
	58.o \
	59.o \
	60.o \
	61.o \
	62.o \
	63.o \
	64.o \
	65.o \
	66.o \
	67.o \
	68.o \
	69.o \
	70.o \
	71.o \
	72.o \
	73.o \
	74.o \
	75.o \
	76.o \
	77.o \
	78.o \
	79.o \
	80.o \
	81.o \
	82.o \
	83.o \
	84.o \
	85.o \
	86.o \
	87.o \
	88.o \
	89.o \
	90.o \
	91.o \
	92.o \
	93.o \
	94.o \
	95.o \
	96.o \
	97.o \
	98.o \
	99.o \
	-o main


clean:
	rm -f main *.o *~

